title: My GitHub Page
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://rafaelmguimaraes.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: https://twitter.com/rafamguimaraes #if your site has a twitter account, enter it here

# Author Settings
author: Rafael Machado Guimarães # add your name
author-img: rafael-guimaraes.jpg # add your photo
about-author: I'm a digital nomad, studying new web development technologies and data science. # add description
social-whats: 5571999444521 # add your Twitter handle
social-github: rafaelmguimaraes # add your Github handle
social-linkedin: rafaelmguimaraes # add your Linkedin handle
social-email: rafaelmguimaraes@gmail.com # add your Email address
social-blog: blog # add your Facebook handle

# Disqus
discus-identifier: rafaelmachadoguimares # add your discus identifier

# Tracker
analytics: UA-178130113-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
